import { createFileRoute } from "@tanstack/react-router";
import { Armchair, Check, Crown } from "lucide-react";
import { useState } from "react";
import { PageTitle, Seat } from "@/components/cinema";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/booking")({ validateSearch: (search: Record<string, unknown>) => ({ time: typeof search["time"] === "string" ? search["time"] : "19:10" }), head: () => ({ meta: [{ title: "Выбор мест — Аврора" }, { name: "description", content: "Выберите места в кинозале и подготовьте заказ к оплате." }, { property: "og:title", content: "Выбор мест — Аврора" }, { property: "og:description", content: "Интерактивная схема зала кинотеатра Аврора." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: BookingPage });
const taken = new Set(["2-4", "2-5", "3-8", "4-2", "5-7", "6-4", "6-5"]);
function BookingPage() { const { time } = Route.useSearch(); const [selected, setSelected] = useState<string[]>(["5-5", "5-6"]); const toggle = (seat: string) => setSelected((prev) => prev.includes(seat) ? prev.filter((item) => item !== seat) : [...prev, seat]); const total = selected.reduce((sum, seat) => sum + (Number(seat.split("-")[0]) >= 6 ? 750 : 550), 0);
return <main className="page-shell py-10 md:py-14"><PageTitle eyebrow="Дюна: Часть вторая" title="ВЫБОР МЕСТ" description={`Сегодня, ${time} · Зал 1 · 2D`}/><div className="grid gap-8 xl:grid-cols-[1fr_340px]"><section className="panel overflow-x-auto p-5 md:p-8"><div className="mx-auto min-w-[560px] max-w-3xl"><div className="mx-auto mb-12 h-12 w-4/5 border-t-4 border-primary text-center text-xs text-muted-foreground [transform:perspective(250px)_rotateX(-20deg)]"><span className="relative -top-7">ЭКРАН</span></div><div className="grid gap-3">{Array.from({ length: 7 }, (_, rowIndex) => { const row = rowIndex + 1; return <div key={row} className="flex items-center justify-center gap-2"><span className="mr-2 w-5 text-xs text-muted-foreground">{row}</span>{Array.from({ length: 12 }, (_, seatIndex) => { const num = seatIndex + 1; const id = `${row}-${num}`; return <Seat key={id} label={String(num)} state={taken.has(id) ? "taken" : row >= 6 ? "vip" : "free"} selected={selected.includes(id)} onClick={() => toggle(id)}/>})}</div>})}</div><div className="mt-10 flex flex-wrap justify-center gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Armchair className="size-4"/>Свободно</span><span className="flex items-center gap-2 text-primary"><Check className="size-4"/>Выбрано</span><span className="flex items-center gap-2 opacity-40"><Armchair className="size-4"/>Занято</span><span className="flex items-center gap-2 text-gold"><Crown className="size-4"/>VIP</span></div></div></section><aside className="panel h-fit p-5 xl:sticky xl:top-20"><p className="eyebrow">Ваш заказ</p><h2 className="font-display text-3xl">Дюна: Часть вторая</h2><div className="mt-5 border-y border-border py-4 text-sm text-muted-foreground"><p>Сегодня, {time}</p><p>Зал 1 · 2D</p></div><div className="my-5 min-h-24">{selected.length ? selected.map((seat) => { const [row, number] = seat.split("-"); return <div key={seat} className="flex justify-between py-2 text-sm"><span>Ряд {row}, место {number}</span><span>{Number(row) >= 6 ? 750 : 550} ₽</span></div>}) : <p className="text-sm text-muted-foreground">Выберите места на схеме</p>}</div><div className="flex justify-between border-t border-border pt-5"><b>Итого</b><b className="text-xl">{total.toLocaleString("ru-RU")} ₽</b></div><Button className="mt-5 h-12 w-full rounded-full" disabled={!selected.length}>Оплатить</Button><p className="mt-3 text-center text-xs text-muted-foreground">Бронь удерживается 10 минут</p></aside></div></main>; }
