import { createFileRoute } from "@tanstack/react-router";
import { Banknote, CalendarDays, CreditCard, RotateCcw, Search, TicketCheck } from "lucide-react";
import { useState } from "react";
import { Badge, PageTitle, SessionPill } from "@/components/cinema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/cashier")({ head: () => ({ meta: [{ title: "Касса — Аврора" }, { name: "description", content: "Рабочее место кассира кинотеатра Аврора." }, { property: "og:title", content: "Касса — Аврора" }, { property: "og:description", content: "Продажа и возврат билетов в кинотеатре Аврора." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CashierPage });
function CashierPage() { const [session, setSession] = useState("19:10"); return <main className="page-shell py-8 md:py-12"><PageTitle eyebrow="Рабочее место" title="КАССА" description="Смена №184 · Кассир: Марина К."/><div className="grid gap-6 xl:grid-cols-[1fr_330px]"><section><div className="panel grid gap-3 p-4 sm:grid-cols-[1fr_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="h-11 pl-10" placeholder="Фильм, номер заказа или билет"/></label><Button variant="outline"><CalendarDays/>Сегодня, 1 октября</Button></div><div className="mt-5 grid gap-3">{["Дюна: Часть вторая", "Падение империи", "Каскадёры"].map((film, index) => <article key={film} className="panel p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl">{film}</h2><p className="text-xs text-muted-foreground">Зал {index + 1} · 2D · {166 - index * 12} мин</p></div><Badge tone={index === 0 ? "green" : "blue"}>{index === 0 ? "Идёт продажа" : "Доступно"}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{["11:20", "15:40", "19:10", "22:30"].map((time) => <SessionPill key={time} selected={session === time} onClick={() => setSession(time)}>{time}</SessionPill>)}</div></article>)}</div></section><aside className="panel h-fit p-5 xl:sticky xl:top-20"><p className="eyebrow">Текущий заказ</p><h2 className="font-display text-3xl">Дюна: Часть вторая</h2><p className="mt-1 text-sm text-muted-foreground">Сегодня, {session} · Зал 1</p><div className="my-5 space-y-2 border-y border-border py-4 text-sm"><div className="flex justify-between"><span>Ряд 7, место 8</span><span>550 ₽</span></div><div className="flex justify-between"><span>Ряд 7, место 9</span><span>550 ₽</span></div></div><div className="flex justify-between"><b>К оплате</b><b className="text-xl">1 100 ₽</b></div><div className="mt-5 grid grid-cols-2 gap-2"><Button><CreditCard/>Картой</Button><Button variant="secondary"><Banknote/>Наличными</Button></div><Button variant="outline" className="mt-2 w-full"><TicketCheck/>Продать билет</Button><Button variant="ghost" className="mt-5 w-full text-destructive"><RotateCcw/>Оформить возврат</Button></aside></div></main>; }
