import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, ScanBarcode, XCircle } from "lucide-react";
import { useState } from "react";
import { PageTitle } from "@/components/cinema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/controller")({ head: () => ({ meta: [{ title: "Контроль билетов — Аврора" }, { name: "description", content: "Проверка электронных билетов кинотеатра Аврора." }, { property: "og:title", content: "Контроль билетов — Аврора" }, { property: "og:description", content: "Экран проверки билетов кинотеатра Аврора." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ControllerPage });
function ControllerPage() { const [code, setCode] = useState(""); const [status, setStatus] = useState<"idle" | "valid" | "invalid">("idle"); const check = () => setStatus(code.trim().toUpperCase().startsWith("AVR") ? "valid" : "invalid"); return <main className="page-shell py-10 md:py-16"><PageTitle eyebrow="Вход в зал" title="КОНТРОЛЬ БИЛЕТОВ" description="Отсканируйте штрихкод или введите номер вручную."/><section className="mx-auto max-w-3xl"><form className="panel flex flex-col gap-3 p-4 sm:flex-row" onSubmit={(e) => { e.preventDefault(); check(); }}><label className="relative flex-1"><ScanBarcode className="absolute left-4 top-1/2 size-6 -translate-y-1/2 text-primary"/><Input autoFocus value={code} onChange={(e) => setCode(e.target.value)} className="h-16 pl-13 text-lg" placeholder="Например, AVR-2405-1908"/></label><Button className="h-16 rounded-xl px-8">Проверить</Button></form>{status === "valid" && <article className="mt-6 rounded-[14px] border border-success bg-success/10 p-8 text-center"><CheckCircle2 className="mx-auto size-14 text-success"/><h2 className="mt-4 font-display text-5xl text-success">БИЛЕТ ДЕЙСТВИТЕЛЕН</h2><div className="mx-auto mt-6 grid max-w-xl grid-cols-2 gap-4 border-t border-success/20 pt-6 text-left sm:grid-cols-4"><span><small className="block text-muted-foreground">Фильм</small>Дюна 2</span><span><small className="block text-muted-foreground">Сеанс</small>19:10</span><span><small className="block text-muted-foreground">Зал</small>1</span><span><small className="block text-muted-foreground">Места</small>7 ряд, 8–9</span></div></article>}{status === "invalid" && <article className="mt-6 rounded-[14px] border border-destructive bg-destructive/10 p-8 text-center"><XCircle className="mx-auto size-14 text-destructive"/><h2 className="mt-4 font-display text-5xl text-destructive">БИЛЕТ НЕДЕЙСТВИТЕЛЕН</h2><p className="mt-2 text-muted-foreground">Код не найден. Проверьте номер и попробуйте снова.</p></article>}{status === "idle" && <div className="mt-6 rounded-[14px] border border-dashed border-border p-12 text-center text-muted-foreground"><ScanBarcode className="mx-auto mb-4 size-12 opacity-40"/><p>Результат проверки появится здесь</p></div>}</section></main>; }
