import { createFileRoute, Link } from "@tanstack/react-router";
import { Clock3, Play, Star } from "lucide-react";
import { Badge, SessionPill } from "@/components/cinema";
import { Button } from "@/components/ui/button";
import { films } from "@/lib/cinema-data";

export const Route = createFileRoute("/movie/$slug")({
  head: ({ params }) => { const film = films.find((item) => item.slug === params.slug) ?? films[0]; return { meta: [{ title: `${film.title} — Аврора` }, { name: "description", content: `Описание, актёры и сеансы фильма «${film.title}» в кинотеатре Аврора.` }, { property: "og:title", content: `${film.title} — Аврора` }, { property: "og:description", content: `Купить билеты на фильм «${film.title}».` }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }; },
  component: MoviePage,
});
function MoviePage() { const { slug } = Route.useParams(); const film = films.find((item) => item.slug === slug) ?? films[0]; return <main><section className="relative overflow-hidden"><img src={film.backdrop} alt="Фон фильма" className="absolute inset-0 h-full w-full object-cover opacity-25 blur-sm"/><div className="absolute inset-0 bg-background/70"/><div className="page-shell relative grid gap-8 py-12 md:grid-cols-[280px_1fr] md:py-20"><img src={film.poster} alt={`Постер «${film.title}»`} className="aspect-[2/3] w-full max-w-[280px] rounded-[14px] object-cover shadow-2xl"/><div className="self-end"><div className="flex gap-2"><Badge tone="gold"><Star className="mr-1 size-3 fill-current"/>{film.rating}</Badge><Badge>{film.age}</Badge></div><h1 className="mt-5 font-display text-6xl leading-none md:text-8xl">{film.title}</h1><p className="mt-3 text-muted-foreground">{film.genre} · 2024 · США, Канада</p><p className="mt-6 max-w-2xl leading-7 text-muted-foreground">Герой вступает на путь, который изменит судьбу целого мира. Масштабная история о выборе, власти и цене будущего, снятая для большого экрана.</p><div className="mt-7 flex flex-wrap gap-3"><Button className="rounded-full"><Play/>Смотреть трейлер</Button><Button variant="outline" className="rounded-full"><Clock3/>2 ч 46 мин</Button></div><div className="mt-8"><span className="text-xs uppercase text-muted-foreground">В ролях</span><p className="mt-2">Тимоти Шаламе, Зендея, Ребекка Фергюсон, Хавьер Бардем</p></div></div></div></section>
<section className="page-shell py-16"><div className="section-rule mb-5"/><p className="eyebrow">Расписание</p><h2 className="font-display text-5xl">СЕАНСЫ</h2><div className="mt-8 grid gap-4"><div className="panel p-5"><h3 className="font-semibold">Сегодня, 1 октября</h3><div className="mt-4 flex flex-wrap gap-3">{["11:20", "15:40", "19:10", "22:30"].map((time, i) => <Link key={time} to="/booking" search={{ time }}><SessionPill><span className="block text-base">{time}</span><span className="text-[10px] text-muted-foreground">Зал {i % 2 + 1} · {i > 1 ? 650 : 550} ₽</span></SessionPill></Link>)}</div></div><div className="panel p-5"><h3 className="font-semibold">Завтра, 2 октября</h3><div className="mt-4 flex flex-wrap gap-3">{["10:30", "14:10", "18:20", "21:40"].map((time, i) => <Link key={time} to="/booking" search={{ time }}><SessionPill><span className="block text-base">{time}</span><span className="text-[10px] text-muted-foreground">Зал {i % 2 + 1} · 550 ₽</span></SessionPill></Link>)}</div></div></div></section></main>; }
