import { createFileRoute } from "@tanstack/react-router";
import { CreditCard, History, Settings, Ticket } from "lucide-react";
import { useState } from "react";
import { PageTitle, TicketStub } from "@/components/cinema";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/profile")({ head: () => ({ meta: [{ title: "Мои билеты — Аврора" }, { name: "description", content: "Активные билеты, история заказов и настройки профиля кинотеатра Аврора." }, { property: "og:title", content: "Мои билеты — Аврора" }, { property: "og:description", content: "Личный кабинет гостя кинотеатра Аврора." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ProfilePage });
const tabs = [{ id: "tickets", label: "Активные билеты", icon: Ticket }, { id: "history", label: "История", icon: History }, { id: "payments", label: "Платежи", icon: CreditCard }, { id: "settings", label: "Настройки", icon: Settings }];
function ProfilePage() { const [tab, setTab] = useState("tickets"); return <main className="page-shell py-10 md:py-16"><PageTitle eyebrow="Личный кабинет" title="МОЙ ПРОФИЛЬ" description="Анна Воронцова · anna.v@example.ru"/><div className="grid gap-8 lg:grid-cols-[230px_1fr]"><aside className="flex gap-2 overflow-x-auto lg:flex-col">{tabs.map(({ id, label, icon: Icon }) => <Button key={id} variant={tab === id ? "secondary" : "ghost"} className="justify-start" onClick={() => setTab(id)}><Icon/>{label}</Button>)}</aside><section>{tab === "tickets" && <div><h2 className="font-display text-4xl">АКТИВНЫЕ БИЛЕТЫ</h2><div className="mt-5 grid gap-5"><TicketStub/></div></div>}{tab === "history" && <div><h2 className="font-display text-4xl">ИСТОРИЯ ПОСЕЩЕНИЙ</h2><div className="mt-5 grid gap-5"><TicketStub past/><TicketStub past/></div></div>}{tab === "payments" && <div><h2 className="font-display text-4xl">ПЛАТЕЖИ</h2><div className="panel mt-5 overflow-hidden"><table className="w-full text-left text-sm"><thead className="bg-secondary text-muted-foreground"><tr><th className="p-4">Дата</th><th className="p-4">Заказ</th><th className="p-4">Способ</th><th className="p-4 text-right">Сумма</th></tr></thead><tbody><tr className="border-t"><td className="p-4">01.10.2026</td><td className="p-4">AVR-2405</td><td className="p-4">•• 4242</td><td className="p-4 text-right">1 100 ₽</td></tr><tr className="border-t"><td className="p-4">14.09.2026</td><td className="p-4">AVR-2291</td><td className="p-4">СБП</td><td className="p-4 text-right">650 ₽</td></tr></tbody></table></div></div>}{tab === "settings" && <div><h2 className="font-display text-4xl">НАСТРОЙКИ</h2><form className="panel mt-5 grid max-w-2xl gap-4 p-5 sm:grid-cols-2" onSubmit={(e) => e.preventDefault()}><label className="text-sm">Имя<Input className="mt-2 h-11" defaultValue="Анна"/></label><label className="text-sm">Фамилия<Input className="mt-2 h-11" defaultValue="Воронцова"/></label><label className="text-sm sm:col-span-2">Электронная почта<Input className="mt-2 h-11" defaultValue="anna.v@example.ru"/></label><Button className="mt-2 rounded-full sm:w-fit">Сохранить изменения</Button></form></div>}</section></div></main>; }
